# Generated by Django 3.2.19 on 2023-06-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='tast',
            new_name='task',
        ),
    ]
